[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/LorenzoRimella/TF_intro/blob/main/intro_tensorflow.ipynb)

# TensorFlow: funzionamento e utilizzi pratici

Iniziamo con l'importare le librerie principali. La libreria tensorflow è l'oggetto della presentazione, numpy verrà usata per un confronto, time per calcolare i running times, e matplotlib per i grafici.

In [1]:
import tensorflow as tf

import numpy as np

import time

import matplotlib.pyplot as plt

2026-01-29 08:59:20.676090: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-01-29 08:59:21.799298: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-01-29 08:59:21.799338: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-01-29 08:59:21.808567: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-01-29 08:59:22.296566: I tensorflow/core/platform/cpu_feature_g

Vediamo se abbiamo una GPU disponibile

In [2]:
tf.config.list_physical_devices('GPU')

2026-01-29 08:59:28.612220: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2026-01-29 08:59:31.090240: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2026-01-29 08:59:31.090288: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

## Tensori

Creare un tensore da una lista. 
Notiamo che dobbiamo sempre indicare il tipo di tensore (precisione del computer).

In [3]:
x_from_list_1 = tf.convert_to_tensor([100, 1, 1], dtype = tf.float32)
print("tensore 1 "+"\n", x_from_list_1)

x_from_list_2 = tf.convert_to_tensor([[100, 1], [1, 1]], dtype = tf.float32)
print("tensore 2 "+"\n", x_from_list_2)

x_from_list_3 = tf.convert_to_tensor([[[100, 1, 2], [100, 1, 2], [100, 100, 2]], [[2, 1, 2], [100, 1, 2], [2, 1, 2]]], dtype = tf.float32)
print("tensore 3 "+"\n", x_from_list_3)

2026-01-29 08:59:31.125476: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2026-01-29 08:59:31.125569: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2026-01-29 08:59:31.125587: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2026-01-29 08:59:31.276704: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2026-01-29 08:59:31.276768: I tensorflow/compile

tensore 1 
 tf.Tensor([100.   1.   1.], shape=(3,), dtype=float32)
tensore 2 
 tf.Tensor(
[[100.   1.]
 [  1.   1.]], shape=(2, 2), dtype=float32)
tensore 3 
 tf.Tensor(
[[[100.   1.   2.]
  [100.   1.   2.]
  [100. 100.   2.]]

 [[  2.   1.   2.]
  [100.   1.   2.]
  [  2.   1.   2.]]], shape=(2, 3, 3), dtype=float32)


Possiamo anche crearlo direttamente da un numpy array. Questo può essere utile per comunicare con altre librerie, es. pandas, nella lettura dei dati. 
Notiamo che se non specifico il tipo viene assegnato uno di deafult, in questo caso int perché non ci sono virgole.

In [4]:
npx = np.array([100, 1, 1])

x_from_numpy = tf.convert_to_tensor(npx)
print("tensore da numpy "+"\n", x_from_numpy)

tensore da numpy 
 tf.Tensor([100   1   1], shape=(3,), dtype=int64)


Mentre in un numpy array possiamo cambiare gli elementi

In [5]:
npx = np.array([100, 1, 1])

npx[2] = -100

print("numpy array con nuovo elemento "+"\n", npx)

numpy array con nuovo elemento 
 [ 100    1 -100]


I tensori sono immutabili

In [6]:
npx = np.array([100, 1, 1])

x_from_numpy = tf.convert_to_tensor(npx)

x_from_numpy[2] = -100

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

## Operazioni tra tensori

### Operazioni elemento per elemento

Avere lo stesso tipo (compatibili) di tensori ci permette di eseguire operazioni su di essi, ma se non sono compatibili abbiamo un errore.

In [10]:
x_not_compatible_sum = x_from_numpy + x_from_list_1

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int64 tensor but is a float tensor [Op:AddV2] name: 

Se abbiamo tensori compatibili possiamo sommarli

In [11]:
x_from_numpy_float32 = tf.convert_to_tensor(npx, dtype = tf.float32)
x_compatible_sum = x_from_numpy_float32 + x_from_list_1
print(x_compatible_sum)

tf.Tensor([200.   2.   2.], shape=(3,), dtype=float32)


farne la differenza

In [12]:
x_compatible_diff = x_from_numpy_float32 - x_from_list_1
print(x_compatible_diff)

tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)


moltiplicarli

In [13]:
x_compatible_prod = x_from_numpy_float32 * x_from_list_1
print(x_compatible_prod)

tf.Tensor([1.e+04 1.e+00 1.e+00], shape=(3,), dtype=float32)


dividerli

In [14]:
x_compatible_div = x_from_numpy_float32 / x_from_list_1
print(x_compatible_div)

tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)


e praticamente tutto quello che vogliamo: potenze, logaritmi, esponenziali, e altro... Google it!

In [15]:
x_compatible_pow = tf.math.pow(x_from_numpy_float32, 3)
print(x_compatible_pow)

x_compatible_log = tf.math.log(x_from_numpy_float32)
print(x_compatible_log)

x_compatible_exp = tf.math.exp(x_from_numpy_float32)
print(x_compatible_exp)

2026-01-29 08:59:55.238260: I tensorflow/tsl/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory


tf.Tensor([1.00000006e+06 1.00000000e+00 1.00000000e+00], shape=(3,), dtype=float32)
tf.Tensor([4.6051702 0.        0.       ], shape=(3,), dtype=float32)
tf.Tensor([      inf 2.7182817 2.7182817], shape=(3,), dtype=float32)


### Operazioni di riduzione

A volte vogliamo fare operazioni su dimensioni specifiche di tensori, per es. medie e somme, per farlo abbiamo le operazioni reduce

In [16]:
numpy_array_normal = np.random.normal(0, 1, (1000, 10))
x_normal = tf.convert_to_tensor(numpy_array_normal, dtype = tf.float32)

print("Somma le righe e mantieni la dimensione "+"\n", tf.reduce_sum(x_normal, axis = 0, keepdims = True))
print("Somma le righe "+"\n", tf.reduce_sum(x_normal, axis = 0))

Somma le righe e mantieni la dimensione 
 tf.Tensor(
[[-31.45879    33.876328  -74.253586   -5.8108754 -52.091072   18.724203
   21.157425   12.743502   35.47486    -3.8607616]], shape=(1, 10), dtype=float32)
Somma le righe 
 tf.Tensor(
[-31.45879    33.876328  -74.253586   -5.8108754 -52.091072   18.724203
  21.157425   12.743502   35.47486    -3.8607616], shape=(10,), dtype=float32)


E per la media, massimo, minimo?

In [17]:
print(tf.reduce_mean(x_normal, axis = 0))
print(tf.reduce_max(x_normal, axis = 0))
print(tf.reduce_min(x_normal, axis = 0))

tf.Tensor(
[-0.03145879  0.03387633 -0.07425359 -0.00581088 -0.05209107  0.0187242
  0.02115742  0.0127435   0.03547486 -0.00386076], shape=(10,), dtype=float32)
tf.Tensor(
[2.9985833 3.8766878 3.197682  2.7637267 3.1152568 2.8683956 3.2237716
 2.9459667 3.508057  3.159443 ], shape=(10,), dtype=float32)
tf.Tensor(
[-3.1706328 -3.2983055 -3.1361868 -3.1359913 -3.428623  -3.6864853
 -3.935677  -3.2548006 -2.7182446 -3.4848936], shape=(10,), dtype=float32)


### Broadcasting

Come per numpy possiamo combinare tensori con le stesse dimensioni ma numero di elementi diversi tramite il broadcasting. Qui il tensore più piccolo viene proiettato su quello più grande.

In [18]:
numpy_array_normal_1 = np.random.normal(0, 1, (1000, 10))
x_normal_1 = tf.convert_to_tensor(numpy_array_normal_1, dtype = tf.float32)

numpy_array_normal_2 = np.random.normal(0, 1, (1000, 1))
x_normal_2 = tf.convert_to_tensor(numpy_array_normal_2, dtype = tf.float32)

print("Numero di elementi per dimenisone per il primo tensore "+"\n",   tf.shape(x_normal_1))
print("Numero di elementi per dimenisone per il secondo tensore "+"\n", tf.shape(x_normal_2))
print("Somma del primo tensore con il secondo tensore tramite broadcasting "+"\n", x_normal_1 + x_normal_2)

Numero di elementi per dimenisone per il primo tensore 
 tf.Tensor([1000   10], shape=(2,), dtype=int32)
Numero di elementi per dimenisone per il secondo tensore 
 tf.Tensor([1000    1], shape=(2,), dtype=int32)
Somma del primo tensore con il secondo tensore tramite broadcasting 
 tf.Tensor(
[[-0.6329824  -0.2533936  -0.5351025  ... -0.82629734 -0.8499723
  -1.6239971 ]
 [ 1.0565451   0.42078948  1.3052891  ... -0.10117    -0.28716344
  -0.08061808]
 [ 0.723187    1.2173228  -0.73405254 ...  2.1694133   0.6604266
   1.2830296 ]
 ...
 [ 0.15205757 -0.04761548  0.31708777 ... -0.07093471  0.85323805
   0.07431581]
 [-2.4619832   1.155306   -1.4286293  ...  0.86876893 -0.12824313
   1.484722  ]
 [ 2.9173884   3.2346406   3.0532193  ...  1.4491718   1.9036044
  -0.7789408 ]], shape=(1000, 10), dtype=float32)


Il tensore piccolo deve poter essere replicato un numero esatto di volte senza ambiguità, altrimenti abbiamo un errore.

In [19]:
numpy_array_normal_3 = np.random.normal(0, 1, (1000, 2))
x_normal_3 = tf.convert_to_tensor(numpy_array_normal_3, dtype = tf.float32)

print("Numero di elementi per dimenisone per il primo tensore "+"\n", tf.shape(x_normal_3))
print("Numero di elementi per dimenisone per il secondo tensore "+"\n",tf.shape(x_normal_1) )
print("Somma del primo tensore con il secondo tensore tramite broadcasting "+"\n", x_normal_1 + x_normal_3)

Numero di elementi per dimenisone per il primo tensore 
 tf.Tensor([1000    2], shape=(2,), dtype=int32)
Numero di elementi per dimenisone per il secondo tensore 
 tf.Tensor([1000   10], shape=(2,), dtype=int32)


2026-01-29 08:59:58.531502: W tensorflow/core/framework/op_kernel.cc:1827] INVALID_ARGUMENT: required broadcastable shapes


InvalidArgumentError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} required broadcastable shapes [Op:AddV2] name: 

Possiamo correggere le dimensioni usando expand_dims.

In [20]:
numpy_array_normal_4 = np.random.normal(0, 1, (1000, 100, 10, 50))
x_normal_4 = tf.convert_to_tensor(numpy_array_normal_4, dtype = tf.float32)

print("Numero di elementi per dimenisone per il primo tensore "+"\n", tf.shape(x_normal_1))
print("Numero di elementi per dimenisone per il secondo tensore "+"\n", tf.shape(x_normal_4))

Numero di elementi per dimenisone per il primo tensore 
 tf.Tensor([1000   10], shape=(2,), dtype=int32)
Numero di elementi per dimenisone per il secondo tensore 
 tf.Tensor([1000  100   10   50], shape=(4,), dtype=int32)


Qui per esempio vogliamo espandere la seconda e l'ultima dimensione.

In [21]:
x_normal_expanded = tf.expand_dims(tf.expand_dims(x_normal_1, 1), -1)

print("Somma del primo tensore con il secondo tensore tramite broadcasting "+"\n", tf.reduce_sum(x_normal_expanded + x_normal_4))

Somma del primo tensore con il secondo tensore tramite broadcasting 
 tf.Tensor(540114.94, shape=(), dtype=float32)


Nota che abbiamo portato come esempio la somma, ma il broadcasting funziona anche per differenza, prodotto, e divisione.

### Operazioni tra dimensioni con einsum

La notazione di Einstein ci permette di effettuare operazioni di somma, prodotto, differenza, e divisione tra le dimensioni di tensori multidimensionali. Il caso più banale è il prodotto tra matrici e vettori.

In [22]:
numpy_array_A = np.random.normal(0, 1, (10, 10))
A = tf.convert_to_tensor(numpy_array_A, dtype = tf.float32)

numpy_array_b = np.random.normal(0, 1, (10))
b = tf.convert_to_tensor(numpy_array_b, dtype = tf.float32)

print("Prodotto tra la matrice e il vettore "+"\n", tf.einsum("ij,j->i", A, b))

Prodotto tra la matrice e il vettore 
 tf.Tensor(
[-3.5257294  -2.468877    0.99643743 -1.4330745  -5.08745    -5.1836786
 -1.5357137  -4.377594    1.1905733  -1.7942619 ], shape=(10,), dtype=float32)


Il grosso vantaggio è che possiamo farlo anche su tensori di matrici.

In [23]:
numpy_array_A = np.random.normal(0, 1, (1000, 100, 10, 10))
A = tf.convert_to_tensor(numpy_array_A, dtype = tf.float32)

numpy_array_b = np.random.normal(0, 1, (1000, 100, 10))
b = tf.convert_to_tensor(numpy_array_b, dtype = tf.float32)

print("Prodotto tra tensori di matrici e di vettori "+"\n", tf.einsum("nhij,nhj->nhi", A, b))
print("Prodotto tra tensori di matrici e di vettori "+"\n", tf.einsum("...ij,...j->...i", A, b))

Prodotto tra tensori di matrici e di vettori 
 tf.Tensor(
[[[-2.9194183   1.4348356   1.4062337  ...  5.4584255   7.9114947
    0.41593933]
  [ 0.0102362   0.3842299  -1.7232189  ... -0.18307662 -1.5202118
    2.564653  ]
  [ 2.0685983   2.5460925   1.4458483  ...  3.3978298  -2.5723565
   -2.134503  ]
  ...
  [ 1.8602633   2.1680176   1.675511   ...  1.0009179  -0.7119558
    4.3088503 ]
  [-0.2802956  -6.134557    8.279608   ...  3.3314757  -2.4269292
   -3.6034746 ]
  [-1.0705116   0.8496529   3.4393904  ...  0.01789801  4.4477725
   -4.0888243 ]]

 [[ 2.6605475   1.6431581   4.0256686  ...  4.076202   -6.300973
   -3.7376995 ]
  [ 1.9049526   2.6993823  -1.9047573  ...  5.86748     2.5697565
    3.413865  ]
  [ 0.74447584 -1.9372935   1.0115457  ... -3.9164283   4.1718135
   -0.3182931 ]
  ...
  [ 1.7953453  -1.5467398   1.4451729  ... -3.9533784   1.3394225
    4.273911  ]
  [-0.85293967 -3.186804    2.1247249  ...  0.20896015  7.469268
   -0.60964215]
  [-3.122695    0.15174896  

L'importante è che le dimensioni su cui effettuiamo l'operazione rispettino le dimensioni.

In [24]:
numpy_array_A = np.random.normal(0, 1, (1000, 100, 10, 10))
A = tf.convert_to_tensor(numpy_array_A, dtype = tf.float32)

numpy_array_b = np.random.normal(0, 1, (100, 10))
b = tf.convert_to_tensor(numpy_array_b, dtype = tf.float32)

print("Prodotto tra tensori di matrici e di vettori "+"\n", tf.einsum("...hij,hj->...hi", A, b))

Prodotto tra tensori di matrici e di vettori 
 tf.Tensor(
[[[ 2.9430718  -3.3505454   1.8829994  ... -1.980938   -3.649519
    2.6537714 ]
  [ 1.2129307   1.7160871   3.7076519  ...  6.6553373   0.38693857
    0.19331613]
  [-1.6666896   2.3893676  -4.0232897  ... -1.9163061  -2.8786266
    3.70921   ]
  ...
  [ 0.52798295  1.935235    3.6631703  ... -5.9439173  -1.3582886
   -4.234736  ]
  [-1.9224184   2.381717   -1.7632741  ...  4.1731033   3.425043
    1.2571268 ]
  [-5.7820616   0.32982516 -0.44966853 ... -0.13595901 -1.6004652
    6.1476455 ]]

 [[-2.2108772  -1.7958032   0.38095593 ... -2.0926492   2.5734658
    0.49307203]
  [-0.80312324 -1.0848883  -0.70723504 ... -4.7339706   1.015989
   -2.4657393 ]
  [ 0.9322814  -1.8818929  -1.634514   ...  0.06296545 -3.124466
   -0.634296  ]
  ...
  [ 3.5753555  -3.8374286  -3.3457603  ...  0.42999333 -4.0373697
   -0.5925848 ]
  [-0.7665982  -1.3450924   4.103297   ... -3.0481825   0.6273246
    1.7084079 ]
  [-3.0384617  -1.550501   -0

## Confronti di performance

In [31]:
numpy_array_A = np.random.normal(0, 1, (10000, 100, 10, 10))
A = tf.convert_to_tensor(numpy_array_A, dtype = tf.float32)

numpy_array_b = np.random.normal(0, 1, (10000, 100, 10))
b = tf.convert_to_tensor(numpy_array_b, dtype = tf.float32)

In [32]:
start = time.time()
for n in range(10000):
	for h in range(100):

		np.matmul(numpy_array_A[n,h,...], numpy_array_b[n,h,...])
		
print("Gira in ", time.time()-start)

Gira in  0.802950382232666


In [33]:
start = time.time()
np.einsum("nhij,nhj->nhi", numpy_array_A, numpy_array_b)		
print("Gira in ", time.time()-start)

Gira in  0.06720614433288574


In [34]:
start = time.time()
tf.einsum("nhij,nhj->nhi", A, b)		
print("Gira in ", time.time()-start)

Gira in  0.0011544227600097656
